import { IWorkout } from "../types/workout.type";

const image = "/banner.png";

export const FALLBACK_WORKOUTS: IWorkout[] = [
  { id: 1, name: "Barbell Squat", image, categories: ["LEGS", "STRENGTH"], equipment: "Barbell", duration: 25, calories: 220, rating: 4.9, difficulty: "Intermediate", sets: 4, reps: "6-8", description: "A compound lower-body movement for building strength and stability.", instructions: ["Set the bar securely across your upper back.", "Brace your core and keep your chest controlled.", "Lower until your thighs reach a comfortable depth.", "Drive through your feet to stand tall."] },
  { id: 2, name: "Bench Press", image, categories: ["CHEST", "STRENGTH"], equipment: "Barbell", duration: 20, calories: 180, rating: 4.8, difficulty: "Intermediate", sets: 4, reps: "6-10", description: "A classic pressing movement for chest, shoulders and triceps.", instructions: ["Lie flat with your eyes under the bar.", "Grip the bar slightly wider than shoulder width.", "Lower it with control toward your mid chest.", "Press up while keeping your shoulders stable."] },
  { id: 3, name: "Deadlift", image, categories: ["BACK", "LEGS"], equipment: "Barbell", duration: 25, calories: 260, rating: 4.9, difficulty: "Advanced", sets: 4, reps: "4-6", description: "A full-body strength movement emphasizing the posterior chain.", instructions: ["Stand with the bar over your mid foot.", "Hinge at the hips and brace your core.", "Push the floor away while keeping the bar close.", "Lock out without leaning backward."] },
  { id: 4, name: "Pull Up", image, categories: ["BACK", "ARMS"], equipment: "Pull-up Bar", duration: 15, calories: 150, rating: 4.8, difficulty: "Intermediate", sets: 4, reps: "6-10", description: "A bodyweight pull that develops the upper back and arms.", instructions: ["Grip the bar firmly with your hands outside shoulder width.", "Brace your core and start from a controlled hang.", "Pull your chest toward the bar.", "Lower slowly to the starting position."] },
  { id: 5, name: "Overhead Press", image, categories: ["SHOULDERS", "STRENGTH"], equipment: "Barbell", duration: 18, calories: 160, rating: 4.7, difficulty: "Intermediate", sets: 4, reps: "6-10", description: "A standing press for strong shoulders and upper-body stability.", instructions: ["Start with the bar at upper chest height.", "Brace your abs and squeeze your glutes.", "Press the bar overhead in a straight path.", "Lower it under control to your shoulders."] },
  { id: 6, name: "Barbell Row", image, categories: ["BACK", "STRENGTH"], equipment: "Barbell", duration: 20, calories: 190, rating: 4.8, difficulty: "Intermediate", sets: 4, reps: "8-10", description: "A horizontal pull for building back thickness and strength.", instructions: ["Hinge forward with a neutral spine.", "Brace your core and keep the bar close.", "Pull toward your lower ribs.", "Lower the bar slowly without losing position."] },
  { id: 7, name: "Romanian Deadlift", image, categories: ["HAMSTRINGS", "LEGS"], equipment: "Dumbbells", duration: 18, calories: 170, rating: 4.7, difficulty: "Intermediate", sets: 3, reps: "8-12", description: "A hip-hinge exercise focused on hamstrings and glutes.", instructions: ["Hold the weights close to your thighs.", "Push your hips backward while keeping your back neutral.", "Lower until you feel a strong hamstring stretch.", "Drive your hips forward to return upright."] },
  { id: 8, name: "Dumbbell Lunge", image, categories: ["LEGS", "GLUTES"], equipment: "Dumbbells", duration: 16, calories: 165, rating: 4.7, difficulty: "Beginner", sets: 3, reps: "10 each", description: "A unilateral leg exercise for balance, strength and control.", instructions: ["Stand tall with a dumbbell in each hand.", "Step forward into a controlled lunge.", "Lower until both knees are comfortably bent.", "Push through the front foot and return to standing."] },
  { id: 9, name: "Incline Dumbbell Press", image, categories: ["CHEST", "SHOULDERS"], equipment: "Dumbbells", duration: 18, calories: 155, rating: 4.6, difficulty: "Intermediate", sets: 3, reps: "8-12", description: "An upper-chest focused pressing movement with dumbbells.", instructions: ["Set the bench to a moderate incline.", "Start with the dumbbells above your upper chest.", "Lower them with control and keep your wrists stacked.", "Press back up without bouncing."] },
  { id: 10, name: "Dumbbell Curl", image, categories: ["ARMS", "BICEPS"], equipment: "Dumbbells", duration: 12, calories: 110, rating: 4.6, difficulty: "Beginner", sets: 3, reps: "10-12", description: "A simple isolation movement for controlled biceps work.", instructions: ["Stand tall with your arms at your sides.", "Keep your elbows close to your body.", "Curl the weights without swinging.", "Lower slowly and fully under control."] },
  { id: 11, name: "Triceps Pushdown", image, categories: ["ARMS", "TRICEPS"], equipment: "Cable Machine", duration: 12, calories: 105, rating: 4.6, difficulty: "Beginner", sets: 3, reps: "10-15", description: "A cable isolation exercise for the triceps.", instructions: ["Set the cable around upper-chest height.", "Keep your elbows tucked beside your body.", "Push the handle down until your arms are extended.", "Return slowly without letting your elbows drift forward."] },
  { id: 12, name: "Plank", image, categories: ["CORE", "STABILITY"], equipment: "Bodyweight", duration: 10, calories: 80, rating: 4.5, difficulty: "Beginner", sets: 3, reps: "30-60 sec", description: "A core stability exercise that reinforces full-body bracing.", instructions: ["Place your forearms under your shoulders.", "Extend your legs and keep your body in one line.", "Brace your abs and squeeze your glutes.", "Hold while breathing steadily and maintaining position."] },
];
